apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-postgres
  template:
    metadata:
      labels:
        app: budget-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: budget-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: budget-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budget-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: budget-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: budget-postgres